export const GET_OBJS_SUCCESS = 'GET_OBJS_SUCCESS';
export const GET_OBJS_FAILURE = 'GET_OBJS_FAILURE';

export const GET_MY_OBJS_SUCCESS = 'GET_MY_OBJS_SUCCESS';
export const GET_MY_OBJS_FAILURE = 'GET_MY_OBJS_FAILURE';

export const GET_DETAIL_OBJ_SUCCESS = 'GET_DETAIL_OBJ_SUCCESS';
export const GET_DETAIL_OBJ_FAILURE = 'GET_DETAIL_OBJ_FAILURE';

export const MOVE_TREE_TO_MAP_SUCCESS = 'MOVE_TREE_TO_MAP_SUCCESS';
export const MOVE_TREE_TO_MAP_FAILURE = 'MOVE_TREE_TO_MAP_FAILURE';
export const CLEAR_MOVE_TREE_TO_MAP = 'CLEAR_MOVE_TREE_TO_MAP';

export const GET_ONLAND_OBJS_BY_USERID_SUCCESS = 'GET_ONLAND_OBJS_BY_USERID_SUCCESS';
export const GET_ONLAND_OBJS_BY_USERID_FAILURE = 'GET_ONLAND_OBJS_BY_USERID_FAILURE';

export const REMOVE_OBJS = 'REMOVE_OBJS';

export const UPDATE_OBJS = 'UPDATE_OBJS';

export const SET_TREE_DIES = 'SET_TREE_DIES';

export const GET_OBJS_AREA_SUCCESS = 'GET_OBJS_AREA_SUCCESS';
export const GET_OBJS_AREA_FAILURE = 'GET_OBJS_AREA_FAILURE';